apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/tdemin/debug-kustomize-controller.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux-system
